replicasCount: 3
maxUnavailableCount: 0

image:
  repository: gcr.io/videocoin-network/gateway
  tag: latest
  pullPolicy: Always

config: {}

service:
  type: ClusterIP
  externalHttpPort: 8080
  internalHttpPort: 8080

autoscaler:
  minCount: 1
  maxCount: 10
  targets:
    targetCPUUtilizationPercentage: 70

resources:
  limits:
   cpu: 200m
   memory: 200Mi
  requests:
   cpu: 200m
   memory: 200Mi

secrets:
  sentryDsn: ""

