replicasCount: 1
maxUnavailableCount: 0

image:
  repository: registry.videocoin.net/cloud/gateway
  tag: latest
  pullPolicy: Always
  pullSecrets: 
  - name: regcred

service:
  http: 8080

autoscaler:
  minCount: 1
  maxCount: 3
  targets:
    targetCPUUtilizationPercentage: 70

resources:
  limits:
   cpu: 200m
   memory: 200Mi
  requests:
   cpu: 200m
   memory: 200Mi

ingress:
  enabled: true
  host: console.dev.videocoinapis.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns-prod
    kubernetes.io/ingress.class: nginx
  secret: tls-cert-console-gateway

config:
  GATEWAY_USERSRPCADDR: "users.console.svc.cluster.local:5000"
  GATEWAY_STREAMSRPCADDR: "streams.console.svc.cluster.local:5002"
  GATEWAY_PROFILESRPCADDR: "profiles.console.svc.cluster.local:5004"
  GATEWAY_MINERSRPCADDR: "miners.console.svc.cluster.local:5011"
  GATEWAY_MEDIASERVERRPCADDR: "mediaserver.console.svc.cluster.local:5090"
  GATEWAY_BILLINGRPCADDR: "billing.console.svc.cluster.local:5020"
