replicasCount: 1
maxUnavailableCount: 0

image:
  repository: registry.videocoin.net/cloud/gateway
  tag: latest
  pullPolicy: Always
  pullSecrets: 
  - name: regcred

service:
  type: ClusterIP
  externalHttpPort: 8080
  internalHttpPort: 8080

autoscaler:
  minCount: 1
  maxCount: 3
  targets:
    targetCPUUtilizationPercentage: 70

resources:
  limits:
   cpu: 200m
   memory: 200Mi
  requests:
   cpu: 200m
   memory: 200Mi

config:
  usersRpcAddr: ""
  streamsRpcAddr: ""
  profilesRpcAddr: "profiles.console.svc.cluster.local:5004"
  minersRpcAddr: ""
  msRpcAddr: ""
  billingRpcAddr: ""

secrets:
  sentryDsn: ""

